services:
  page1:
    image: nginx
    networks:
      - jsanches-network
    restart: always
      
  page2:
    image: nginx
    networks:
      - jsanches-network
    restart: always

  proxy:
    image: nginx
    volumes:
      - ./nginx_proxy.conf:/etc/nginx/nginx.conf:ro,z
    ports:
      - "80:80"
    depends_on:
      - page1
      - page2
    networks:
      - jsanches-network
    restart: always

networks:
  jsanches-network:
    driver: bridge
